Docker container names with _ and .
osmhpi/cohydra pull request #26
Opened 2020-02-17 10:35 UTC by felix-gohla

This should fix #25.

We have to modify #6 in order to check for only - as LXC does not support _ and . in container names!

2020-02-17 13:35 UTC, rs22 approved these changes

2020-02-17 14:45 UTC, mgjm requested changes
I think we should still implement some kind of check for all nodes because the node name is used as [part of the pcap file name](../../blob/821ac76/cohydra/interface.py#L98-L107). Therefore we should do some sanity checks to prevent weird paths (e.g. `../lol` as a name).

2020-02-17 15:57 UTC, rs22 commented
With regards to the TLS certificate requirement -- wouldn't it be sufficient to inject additional names for the simulation nodes into their `/etc/hosts` files? I thought you were doing this already (for Docker nodes at least)... 

Then, the names of the containers themselves can continue to be fairly restricted.

2020-02-18 14:14 UTC, felix-gohla commented
Oh right, I totally forgot about the file names.

Maybe we should provide something like `additional_hostnames`?

2020-02-19 11:21 UTC, felix-gohla commented
Now the base class checks the names and file names with `-`, `_` and `.` should be safe. Nevertheless, the `LXDNodes` in #6 need another check.

2020-02-19 16:44 UTC, mgjm approved these changes

2020-02-19 16:48 UTC, mgjm commented on cohydra/node/base.py
> +            if not (char.isalnum() or char in ['-', '_', '.']):
```suggestion
            if not (char.isalnum() or char in '-_.'):
```

2020-02-19 16:51 UTC, merged